{{- if and .Values.backend.enabled .Values.backend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservices-app.fullname" . }}-backend-pdb
  labels:
    {{- include "microservices-app.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.backend.pdb.minAvailable }}
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  {{- else if .Values.backend.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      app: backend
      {{- include "microservices-app.selectorLabels" . | nindent 6 }}
{{- end }}
