apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservices-app.fullname" . }}-secrets
  labels:
    {{- include "microservices-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-username: {{ .Values.secrets.database.username | quote }}
  database-password: {{ .Values.secrets.database.password | quote }}
  api-key: {{ .Values.secrets.backend.apiKey | quote }}
