{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  labels:
    app: kibana
    component: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
  - name: http
    port: {{ .Values.kibana.service.port }}
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana
{{- end }}
