{{- if .Values.logstash.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
  labels:
    app: logstash
    component: logstash
spec:
  type: {{ .Values.logstash.service.type }}
  ports:
  - name: beats
    port: {{ .Values.logstash.service.beats.port }}
    targetPort: 5044
    protocol: TCP
  - name: http
    port: {{ .Values.logstash.service.http.port }}
    targetPort: 8080
    protocol: TCP
  - name: monitoring
    port: 9600
    targetPort: 9600
    protocol: TCP
  selector:
    app: logstash
{{- end }}
